// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mass_weighted_rcpp
List mass_weighted_rcpp(const ComplexVector data_fft, const NumericVector query_window, uint32_t data_size, uint32_t window_size, const NumericVector data_mean, const NumericVector data_sd, double query_mean, double query_sd, const NumericVector data_pre, const NumericVector weight);
RcppExport SEXP _matrixprofiler_mass_weighted_rcpp(SEXP data_fftSEXP, SEXP query_windowSEXP, SEXP data_sizeSEXP, SEXP window_sizeSEXP, SEXP data_meanSEXP, SEXP data_sdSEXP, SEXP query_meanSEXP, SEXP query_sdSEXP, SEXP data_preSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const ComplexVector >::type data_fft(data_fftSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type query_window(query_windowSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type data_size(data_sizeSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type data_mean(data_meanSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type data_sd(data_sdSEXP);
    Rcpp::traits::input_parameter< double >::type query_mean(query_meanSEXP);
    Rcpp::traits::input_parameter< double >::type query_sd(query_sdSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type data_pre(data_preSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type weight(weightSEXP);
    rcpp_result_gen = Rcpp::wrap(mass_weighted_rcpp(data_fft, query_window, data_size, window_size, data_mean, data_sd, query_mean, query_sd, data_pre, weight));
    return rcpp_result_gen;
END_RCPP
}
// mass_absolute_rcpp
List mass_absolute_rcpp(const ComplexVector data_fft, const NumericVector query_window, uint32_t data_size, uint32_t window_size, const NumericVector sumx2, double sumy2);
RcppExport SEXP _matrixprofiler_mass_absolute_rcpp(SEXP data_fftSEXP, SEXP query_windowSEXP, SEXP data_sizeSEXP, SEXP window_sizeSEXP, SEXP sumx2SEXP, SEXP sumy2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const ComplexVector >::type data_fft(data_fftSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type query_window(query_windowSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type data_size(data_sizeSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type sumx2(sumx2SEXP);
    Rcpp::traits::input_parameter< double >::type sumy2(sumy2SEXP);
    rcpp_result_gen = Rcpp::wrap(mass_absolute_rcpp(data_fft, query_window, data_size, window_size, sumx2, sumy2));
    return rcpp_result_gen;
END_RCPP
}
// mass2_rcpp
List mass2_rcpp(const ComplexVector data_fft, const NumericVector query_window, uint64_t data_size, uint32_t window_size, const NumericVector data_mean, const NumericVector data_sd, double query_mean, double query_sd);
RcppExport SEXP _matrixprofiler_mass2_rcpp(SEXP data_fftSEXP, SEXP query_windowSEXP, SEXP data_sizeSEXP, SEXP window_sizeSEXP, SEXP data_meanSEXP, SEXP data_sdSEXP, SEXP query_meanSEXP, SEXP query_sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const ComplexVector >::type data_fft(data_fftSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type query_window(query_windowSEXP);
    Rcpp::traits::input_parameter< uint64_t >::type data_size(data_sizeSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type data_mean(data_meanSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type data_sd(data_sdSEXP);
    Rcpp::traits::input_parameter< double >::type query_mean(query_meanSEXP);
    Rcpp::traits::input_parameter< double >::type query_sd(query_sdSEXP);
    rcpp_result_gen = Rcpp::wrap(mass2_rcpp(data_fft, query_window, data_size, window_size, data_mean, data_sd, query_mean, query_sd));
    return rcpp_result_gen;
END_RCPP
}
// mass3_parallel_rcpp
List mass3_parallel_rcpp(const NumericVector query_window, const NumericVector data_ref, uint64_t data_size, uint32_t window_size, const NumericVector data_mean, const NumericVector data_sd, double query_mean, double query_sd, uint16_t k);
RcppExport SEXP _matrixprofiler_mass3_parallel_rcpp(SEXP query_windowSEXP, SEXP data_refSEXP, SEXP data_sizeSEXP, SEXP window_sizeSEXP, SEXP data_meanSEXP, SEXP data_sdSEXP, SEXP query_meanSEXP, SEXP query_sdSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type query_window(query_windowSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type data_ref(data_refSEXP);
    Rcpp::traits::input_parameter< uint64_t >::type data_size(data_sizeSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type data_mean(data_meanSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type data_sd(data_sdSEXP);
    Rcpp::traits::input_parameter< double >::type query_mean(query_meanSEXP);
    Rcpp::traits::input_parameter< double >::type query_sd(query_sdSEXP);
    Rcpp::traits::input_parameter< uint16_t >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(mass3_parallel_rcpp(query_window, data_ref, data_size, window_size, data_mean, data_sd, query_mean, query_sd, k));
    return rcpp_result_gen;
END_RCPP
}
// mass3_rcpp
List mass3_rcpp(const NumericVector query_window, const NumericVector data_ref, uint64_t data_size, uint32_t window_size, const NumericVector data_mean, const NumericVector data_sd, double query_mean, double query_sd, uint32_t k);
RcppExport SEXP _matrixprofiler_mass3_rcpp(SEXP query_windowSEXP, SEXP data_refSEXP, SEXP data_sizeSEXP, SEXP window_sizeSEXP, SEXP data_meanSEXP, SEXP data_sdSEXP, SEXP query_meanSEXP, SEXP query_sdSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type query_window(query_windowSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type data_ref(data_refSEXP);
    Rcpp::traits::input_parameter< uint64_t >::type data_size(data_sizeSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type data_mean(data_meanSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type data_sd(data_sdSEXP);
    Rcpp::traits::input_parameter< double >::type query_mean(query_meanSEXP);
    Rcpp::traits::input_parameter< double >::type query_sd(query_sdSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(mass3_rcpp(query_window, data_ref, data_size, window_size, data_mean, data_sd, query_mean, query_sd, k));
    return rcpp_result_gen;
END_RCPP
}
// set_k_rcpp
uint32_t set_k_rcpp(uint32_t k, uint64_t data_size, uint64_t window_size);
RcppExport SEXP _matrixprofiler_set_k_rcpp(SEXP kSEXP, SEXP data_sizeSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< uint32_t >::type k(kSEXP);
    Rcpp::traits::input_parameter< uint64_t >::type data_size(data_sizeSEXP);
    Rcpp::traits::input_parameter< uint64_t >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(set_k_rcpp(k, data_size, window_size));
    return rcpp_result_gen;
END_RCPP
}
// find_best_k_rcpp
uint32_t find_best_k_rcpp(const NumericVector data_ref, const NumericVector query_ref, uint32_t window_size);
RcppExport SEXP _matrixprofiler_find_best_k_rcpp(SEXP data_refSEXP, SEXP query_refSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type data_ref(data_refSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type query_ref(query_refSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(find_best_k_rcpp(data_ref, query_ref, window_size));
    return rcpp_result_gen;
END_RCPP
}
// mass_pre_rcpp
List mass_pre_rcpp(const NumericVector data_ref, const NumericVector query_ref, uint32_t window_size);
RcppExport SEXP _matrixprofiler_mass_pre_rcpp(SEXP data_refSEXP, SEXP query_refSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type data_ref(data_refSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type query_ref(query_refSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(mass_pre_rcpp(data_ref, query_ref, window_size));
    return rcpp_result_gen;
END_RCPP
}
// mass_pre_abs_rcpp
List mass_pre_abs_rcpp(const NumericVector data_ref, const NumericVector query_ref, uint32_t window_size);
RcppExport SEXP _matrixprofiler_mass_pre_abs_rcpp(SEXP data_refSEXP, SEXP query_refSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type data_ref(data_refSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type query_ref(query_refSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(mass_pre_abs_rcpp(data_ref, query_ref, window_size));
    return rcpp_result_gen;
END_RCPP
}
// mass_pre_weighted_rcpp
List mass_pre_weighted_rcpp(const NumericVector data_ref, const NumericVector query_ref, uint32_t window_size, const NumericVector weight);
RcppExport SEXP _matrixprofiler_mass_pre_weighted_rcpp(SEXP data_refSEXP, SEXP query_refSEXP, SEXP window_sizeSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type data_ref(data_refSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type query_ref(query_refSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type weight(weightSEXP);
    rcpp_result_gen = Rcpp::wrap(mass_pre_weighted_rcpp(data_ref, query_ref, window_size, weight));
    return rcpp_result_gen;
END_RCPP
}
// std_rcpp
double std_rcpp(const NumericVector data, const bool na_rm);
RcppExport SEXP _matrixprofiler_std_rcpp(SEXP dataSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(std_rcpp(data, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// list_to_matrix
NumericMatrix list_to_matrix(const List x);
RcppExport SEXP _matrixprofiler_list_to_matrix(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(list_to_matrix(x));
    return rcpp_result_gen;
END_RCPP
}
// which
IntegerVector which(const LogicalVector x);
RcppExport SEXP _matrixprofiler_which(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const LogicalVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(which(x));
    return rcpp_result_gen;
END_RCPP
}
// diff_lag
NumericVector diff_lag(const NumericVector x, const uint32_t lag);
RcppExport SEXP _matrixprofiler_diff_lag(SEXP xSEXP, SEXP lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const uint32_t >::type lag(lagSEXP);
    rcpp_result_gen = Rcpp::wrap(diff_lag(x, lag));
    return rcpp_result_gen;
END_RCPP
}
// diff2_lag
NumericVector diff2_lag(const NumericVector x, const uint32_t lag, const double v);
RcppExport SEXP _matrixprofiler_diff2_lag(SEXP xSEXP, SEXP lagSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const uint32_t >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< const double >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(diff2_lag(x, lag, v));
    return rcpp_result_gen;
END_RCPP
}
// fast_movsd_rcpp
NumericVector fast_movsd_rcpp(const NumericVector data, const uint32_t window_size);
RcppExport SEXP _matrixprofiler_fast_movsd_rcpp(SEXP dataSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const uint32_t >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_movsd_rcpp(data, window_size));
    return rcpp_result_gen;
END_RCPP
}
// fast_avg_sd_rcpp
List fast_avg_sd_rcpp(const NumericVector data, const uint32_t window_size);
RcppExport SEXP _matrixprofiler_fast_avg_sd_rcpp(SEXP dataSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const uint32_t >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_avg_sd_rcpp(data, window_size));
    return rcpp_result_gen;
END_RCPP
}
// mode_rcpp
int32_t mode_rcpp(const NumericVector x);
RcppExport SEXP _matrixprofiler_mode_rcpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(mode_rcpp(x));
    return rcpp_result_gen;
END_RCPP
}
// znorm_rcpp
NumericVector znorm_rcpp(const NumericVector data);
RcppExport SEXP _matrixprofiler_znorm_rcpp(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(znorm_rcpp(data));
    return rcpp_result_gen;
END_RCPP
}
// binary_split_rcpp
NumericVector binary_split_rcpp(const uint32_t n);
RcppExport SEXP _matrixprofiler_binary_split_rcpp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const uint32_t >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(binary_split_rcpp(n));
    return rcpp_result_gen;
END_RCPP
}
// inner_product
double inner_product(const NumericVector a, const NumericVector b);
RcppExport SEXP _matrixprofiler_inner_product(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(inner_product(a, b));
    return rcpp_result_gen;
END_RCPP
}
// sum_of_squares
double sum_of_squares(const NumericVector a);
RcppExport SEXP _matrixprofiler_sum_of_squares(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(sum_of_squares(a));
    return rcpp_result_gen;
END_RCPP
}
// fft_rcpp
ComplexVector fft_rcpp(const ComplexVector z, bool invert);
RcppExport SEXP _matrixprofiler_fft_rcpp(SEXP zSEXP, SEXP invertSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const ComplexVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< bool >::type invert(invertSEXP);
    rcpp_result_gen = Rcpp::wrap(fft_rcpp(z, invert));
    return rcpp_result_gen;
END_RCPP
}
// mpx_rcpp
List mpx_rcpp(NumericVector a, uint16_t w, uint16_t minlag, bool idxs, bool euclidean);
RcppExport SEXP _matrixprofiler_mpx_rcpp(SEXP aSEXP, SEXP wSEXP, SEXP minlagSEXP, SEXP idxsSEXP, SEXP euclideanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< uint16_t >::type w(wSEXP);
    Rcpp::traits::input_parameter< uint16_t >::type minlag(minlagSEXP);
    Rcpp::traits::input_parameter< bool >::type idxs(idxsSEXP);
    Rcpp::traits::input_parameter< bool >::type euclidean(euclideanSEXP);
    rcpp_result_gen = Rcpp::wrap(mpx_rcpp(a, w, minlag, idxs, euclidean));
    return rcpp_result_gen;
END_RCPP
}
// mpxab_rcpp
List mpxab_rcpp(NumericVector a, NumericVector b, uint16_t w, bool idxs, bool euclidean);
RcppExport SEXP _matrixprofiler_mpxab_rcpp(SEXP aSEXP, SEXP bSEXP, SEXP wSEXP, SEXP idxsSEXP, SEXP euclideanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< uint16_t >::type w(wSEXP);
    Rcpp::traits::input_parameter< bool >::type idxs(idxsSEXP);
    Rcpp::traits::input_parameter< bool >::type euclidean(euclideanSEXP);
    rcpp_result_gen = Rcpp::wrap(mpxab_rcpp(a, b, w, idxs, euclidean));
    return rcpp_result_gen;
END_RCPP
}
// mpx_rcpp_parallel
List mpx_rcpp_parallel(NumericVector a, uint16_t w, uint16_t minlag, bool idxs, bool euclidean);
RcppExport SEXP _matrixprofiler_mpx_rcpp_parallel(SEXP aSEXP, SEXP wSEXP, SEXP minlagSEXP, SEXP idxsSEXP, SEXP euclideanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< uint16_t >::type w(wSEXP);
    Rcpp::traits::input_parameter< uint16_t >::type minlag(minlagSEXP);
    Rcpp::traits::input_parameter< bool >::type idxs(idxsSEXP);
    Rcpp::traits::input_parameter< bool >::type euclidean(euclideanSEXP);
    rcpp_result_gen = Rcpp::wrap(mpx_rcpp_parallel(a, w, minlag, idxs, euclidean));
    return rcpp_result_gen;
END_RCPP
}
// mpxab_rcpp_parallel
List mpxab_rcpp_parallel(NumericVector a, NumericVector b, uint16_t w, bool idxs, bool euclidean);
RcppExport SEXP _matrixprofiler_mpxab_rcpp_parallel(SEXP aSEXP, SEXP bSEXP, SEXP wSEXP, SEXP idxsSEXP, SEXP euclideanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< uint16_t >::type w(wSEXP);
    Rcpp::traits::input_parameter< bool >::type idxs(idxsSEXP);
    Rcpp::traits::input_parameter< bool >::type euclidean(euclideanSEXP);
    rcpp_result_gen = Rcpp::wrap(mpxab_rcpp_parallel(a, b, w, idxs, euclidean));
    return rcpp_result_gen;
END_RCPP
}
// stamp_cpp
List stamp_cpp(const NumericVector data_ref, const NumericVector query_ref, uint32_t window_size, double ez);
RcppExport SEXP _matrixprofiler_stamp_cpp(SEXP data_refSEXP, SEXP query_refSEXP, SEXP window_sizeSEXP, SEXP ezSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type data_ref(data_refSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type query_ref(query_refSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type ez(ezSEXP);
    rcpp_result_gen = Rcpp::wrap(stamp_cpp(data_ref, query_ref, window_size, ez));
    return rcpp_result_gen;
END_RCPP
}
// stamp_par_cpp
List stamp_par_cpp(const NumericVector data_ref, const NumericVector query_ref, uint32_t window_size, double ez);
RcppExport SEXP _matrixprofiler_stamp_par_cpp(SEXP data_refSEXP, SEXP query_refSEXP, SEXP window_sizeSEXP, SEXP ezSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type data_ref(data_refSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type query_ref(query_refSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type ez(ezSEXP);
    rcpp_result_gen = Rcpp::wrap(stamp_par_cpp(data_ref, query_ref, window_size, ez));
    return rcpp_result_gen;
END_RCPP
}
// stomp_cpp
List stomp_cpp(const NumericVector data_ref, const NumericVector query_ref, uint32_t window_size, double ez);
RcppExport SEXP _matrixprofiler_stomp_cpp(SEXP data_refSEXP, SEXP query_refSEXP, SEXP window_sizeSEXP, SEXP ezSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type data_ref(data_refSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type query_ref(query_refSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type ez(ezSEXP);
    rcpp_result_gen = Rcpp::wrap(stomp_cpp(data_ref, query_ref, window_size, ez));
    return rcpp_result_gen;
END_RCPP
}
// movsum
NumericVector movsum(NumericVector data, uint32_t window_size);
RcppExport SEXP _matrixprofiler_movsum(SEXP dataSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(movsum(data, window_size));
    return rcpp_result_gen;
END_RCPP
}
// movmin
NumericVector movmin(const NumericVector data, uint32_t window_size);
RcppExport SEXP _matrixprofiler_movmin(SEXP dataSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(movmin(data, window_size));
    return rcpp_result_gen;
END_RCPP
}
// movmax
NumericVector movmax(const NumericVector data, uint32_t window_size);
RcppExport SEXP _matrixprofiler_movmax(SEXP dataSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(movmax(data, window_size));
    return rcpp_result_gen;
END_RCPP
}
// mov_mean_online_rcpp
NumericVector mov_mean_online_rcpp(const NumericVector data, uint32_t window_size, double eps);
RcppExport SEXP _matrixprofiler_mov_mean_online_rcpp(SEXP dataSEXP, SEXP window_sizeSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(mov_mean_online_rcpp(data, window_size, eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_matrixprofiler_mass_weighted_rcpp", (DL_FUNC) &_matrixprofiler_mass_weighted_rcpp, 10},
    {"_matrixprofiler_mass_absolute_rcpp", (DL_FUNC) &_matrixprofiler_mass_absolute_rcpp, 6},
    {"_matrixprofiler_mass2_rcpp", (DL_FUNC) &_matrixprofiler_mass2_rcpp, 8},
    {"_matrixprofiler_mass3_parallel_rcpp", (DL_FUNC) &_matrixprofiler_mass3_parallel_rcpp, 9},
    {"_matrixprofiler_mass3_rcpp", (DL_FUNC) &_matrixprofiler_mass3_rcpp, 9},
    {"_matrixprofiler_set_k_rcpp", (DL_FUNC) &_matrixprofiler_set_k_rcpp, 3},
    {"_matrixprofiler_find_best_k_rcpp", (DL_FUNC) &_matrixprofiler_find_best_k_rcpp, 3},
    {"_matrixprofiler_mass_pre_rcpp", (DL_FUNC) &_matrixprofiler_mass_pre_rcpp, 3},
    {"_matrixprofiler_mass_pre_abs_rcpp", (DL_FUNC) &_matrixprofiler_mass_pre_abs_rcpp, 3},
    {"_matrixprofiler_mass_pre_weighted_rcpp", (DL_FUNC) &_matrixprofiler_mass_pre_weighted_rcpp, 4},
    {"_matrixprofiler_std_rcpp", (DL_FUNC) &_matrixprofiler_std_rcpp, 2},
    {"_matrixprofiler_list_to_matrix", (DL_FUNC) &_matrixprofiler_list_to_matrix, 1},
    {"_matrixprofiler_which", (DL_FUNC) &_matrixprofiler_which, 1},
    {"_matrixprofiler_diff_lag", (DL_FUNC) &_matrixprofiler_diff_lag, 2},
    {"_matrixprofiler_diff2_lag", (DL_FUNC) &_matrixprofiler_diff2_lag, 3},
    {"_matrixprofiler_fast_movsd_rcpp", (DL_FUNC) &_matrixprofiler_fast_movsd_rcpp, 2},
    {"_matrixprofiler_fast_avg_sd_rcpp", (DL_FUNC) &_matrixprofiler_fast_avg_sd_rcpp, 2},
    {"_matrixprofiler_mode_rcpp", (DL_FUNC) &_matrixprofiler_mode_rcpp, 1},
    {"_matrixprofiler_znorm_rcpp", (DL_FUNC) &_matrixprofiler_znorm_rcpp, 1},
    {"_matrixprofiler_binary_split_rcpp", (DL_FUNC) &_matrixprofiler_binary_split_rcpp, 1},
    {"_matrixprofiler_inner_product", (DL_FUNC) &_matrixprofiler_inner_product, 2},
    {"_matrixprofiler_sum_of_squares", (DL_FUNC) &_matrixprofiler_sum_of_squares, 1},
    {"_matrixprofiler_fft_rcpp", (DL_FUNC) &_matrixprofiler_fft_rcpp, 2},
    {"_matrixprofiler_mpx_rcpp", (DL_FUNC) &_matrixprofiler_mpx_rcpp, 5},
    {"_matrixprofiler_mpxab_rcpp", (DL_FUNC) &_matrixprofiler_mpxab_rcpp, 5},
    {"_matrixprofiler_mpx_rcpp_parallel", (DL_FUNC) &_matrixprofiler_mpx_rcpp_parallel, 5},
    {"_matrixprofiler_mpxab_rcpp_parallel", (DL_FUNC) &_matrixprofiler_mpxab_rcpp_parallel, 5},
    {"_matrixprofiler_stamp_cpp", (DL_FUNC) &_matrixprofiler_stamp_cpp, 4},
    {"_matrixprofiler_stamp_par_cpp", (DL_FUNC) &_matrixprofiler_stamp_par_cpp, 4},
    {"_matrixprofiler_stomp_cpp", (DL_FUNC) &_matrixprofiler_stomp_cpp, 4},
    {"_matrixprofiler_movsum", (DL_FUNC) &_matrixprofiler_movsum, 2},
    {"_matrixprofiler_movmin", (DL_FUNC) &_matrixprofiler_movmin, 2},
    {"_matrixprofiler_movmax", (DL_FUNC) &_matrixprofiler_movmax, 2},
    {"_matrixprofiler_mov_mean_online_rcpp", (DL_FUNC) &_matrixprofiler_mov_mean_online_rcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_matrixprofiler(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
