# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mass_weighted_rcpp <- function(data_fft, query_window, data_size, window_size, data_mean, data_sd, query_mean, query_sd, data_pre, weight, fft) {
    .Call(`_matrixprofiler_mass_weighted_rcpp`, data_fft, query_window, data_size, window_size, data_mean, data_sd, query_mean, query_sd, data_pre, weight, fft)
}

mass_absolute_rcpp <- function(data_fft, query_window, data_size, window_size, sumx2, sumy2, fft) {
    .Call(`_matrixprofiler_mass_absolute_rcpp`, data_fft, query_window, data_size, window_size, sumx2, sumy2, fft)
}

mass2_rcpp <- function(data_fft, query_window, data_size, window_size, data_mean, data_sd, query_mean, query_sd, fft) {
    .Call(`_matrixprofiler_mass2_rcpp`, data_fft, query_window, data_size, window_size, data_mean, data_sd, query_mean, query_sd, fft)
}

mass3_rcpp <- function(query_window, data_ref, data_size, window_size, data_mean, data_sd, query_mean, query_sd, fft, k) {
    .Call(`_matrixprofiler_mass3_rcpp`, query_window, data_ref, data_size, window_size, data_mean, data_sd, query_mean, query_sd, fft, k)
}

set_k <- function(k, data_size, window_size) {
    .Call(`_matrixprofiler_set_k`, k, data_size, window_size)
}

find_best_k <- function(data_ref, query_ref, window_size) {
    .Call(`_matrixprofiler_find_best_k`, data_ref, query_ref, window_size)
}

mass_pre_rcpp <- function(data_ref, query_ref, window_size) {
    .Call(`_matrixprofiler_mass_pre_rcpp`, data_ref, query_ref, window_size)
}

mass_pre_abs_rcpp <- function(data_ref, query_ref, window_size) {
    .Call(`_matrixprofiler_mass_pre_abs_rcpp`, data_ref, query_ref, window_size)
}

mass_pre_weighted_rcpp <- function(data_ref, query_ref, window_size, weight) {
    .Call(`_matrixprofiler_mass_pre_weighted_rcpp`, data_ref, query_ref, window_size, weight)
}

std_rcpp <- function(data, na_rm = FALSE) {
    .Call(`_matrixprofiler_std_rcpp`, data, na_rm)
}

list_to_matrix <- function(x) {
    .Call(`_matrixprofiler_list_to_matrix`, x)
}

which <- function(x) {
    .Call(`_matrixprofiler_which`, x)
}

diff_lag <- function(x, lag = 1L) {
    .Call(`_matrixprofiler_diff_lag`, x, lag)
}

diff2_lag <- function(x, lag = 1L, v = 0.0) {
    .Call(`_matrixprofiler_diff2_lag`, x, lag, v)
}

fast_movsd_rcpp <- function(data, window_size) {
    .Call(`_matrixprofiler_fast_movsd_rcpp`, data, window_size)
}

fast_avg_sd_rcpp <- function(data, window_size) {
    .Call(`_matrixprofiler_fast_avg_sd_rcpp`, data, window_size)
}

mode_rcpp <- function(x) {
    .Call(`_matrixprofiler_mode_rcpp`, x)
}

znorm_rcpp <- function(data) {
    .Call(`_matrixprofiler_znorm_rcpp`, data)
}

binary_split_rcpp <- function(n) {
    .Call(`_matrixprofiler_binary_split_rcpp`, n)
}

inner_product <- function(a, b) {
    .Call(`_matrixprofiler_inner_product`, a, b)
}

sum_of_squares <- function(a) {
    .Call(`_matrixprofiler_sum_of_squares`, a)
}

mpx_rcpp <- function(a, w, minlag, idxs = FALSE, euclidean = TRUE) {
    .Call(`_matrixprofiler_mpx_rcpp`, a, w, minlag, idxs, euclidean)
}

mpxab_rcpp <- function(a, b, w, idxs = FALSE, euclidean = TRUE) {
    .Call(`_matrixprofiler_mpxab_rcpp`, a, b, w, idxs, euclidean)
}

mpx_rcpp_parallel <- function(a, w, minlag, idxs = FALSE, euclidean = TRUE) {
    .Call(`_matrixprofiler_mpx_rcpp_parallel`, a, w, minlag, idxs, euclidean)
}

mpxab_rcpp_parallel <- function(a, b, w, idxs = FALSE, euclidean = TRUE) {
    .Call(`_matrixprofiler_mpxab_rcpp_parallel`, a, b, w, idxs, euclidean)
}

stamp_cpp <- function(data_ref, query_ref, window_size, ez) {
    .Call(`_matrixprofiler_stamp_cpp`, data_ref, query_ref, window_size, ez)
}

stomp_cpp <- function(data_ref, query_ref, window_size, ez) {
    .Call(`_matrixprofiler_stomp_cpp`, data_ref, query_ref, window_size, ez)
}

movsum <- function(data, window_size) {
    .Call(`_matrixprofiler_movsum`, data, window_size)
}

movmin <- function(data, window_size) {
    .Call(`_matrixprofiler_movmin`, data, window_size)
}

movmax <- function(data, window_size) {
    .Call(`_matrixprofiler_movmax`, data, window_size)
}

mov_mean_online_rcpp <- function(data, window_size, eps = 0.19) {
    .Call(`_matrixprofiler_mov_mean_online_rcpp`, data, window_size, eps)
}

