# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mass_weighted_rcpp <- function(data_fft, query_window, data_size, window_size, data_mean, data_sd, query_mean, query_sd, data_pre, weight) {
    .Call(`_matrixprofiler_mass_weighted_rcpp`, data_fft, query_window, data_size, window_size, data_mean, data_sd, query_mean, query_sd, data_pre, weight)
}

mass_absolute_rcpp <- function(data_fft, query_window, data_size, window_size, sumx2, sumy2) {
    .Call(`_matrixprofiler_mass_absolute_rcpp`, data_fft, query_window, data_size, window_size, sumx2, sumy2)
}

mass2_rcpp <- function(data_fft, query_window, data_size, window_size, data_mean, data_sd, query_mean, query_sd) {
    .Call(`_matrixprofiler_mass2_rcpp`, data_fft, query_window, data_size, window_size, data_mean, data_sd, query_mean, query_sd)
}

mass3_rcpp_parallel <- function(query_window, data_ref, data_size, window_size, data_mean, data_sd, query_mean, query_sd, k) {
    .Call(`_matrixprofiler_mass3_rcpp_parallel`, query_window, data_ref, data_size, window_size, data_mean, data_sd, query_mean, query_sd, k)
}

mass3_rcpp <- function(query_window, data_ref, data_size, window_size, data_mean, data_sd, query_mean, query_sd, k) {
    .Call(`_matrixprofiler_mass3_rcpp`, query_window, data_ref, data_size, window_size, data_mean, data_sd, query_mean, query_sd, k)
}

set_k_rcpp <- function(k, data_size, window_size) {
    .Call(`_matrixprofiler_set_k_rcpp`, k, data_size, window_size)
}

find_best_k_rcpp <- function(data_ref, query_ref, window_size) {
    .Call(`_matrixprofiler_find_best_k_rcpp`, data_ref, query_ref, window_size)
}

mass_pre_rcpp <- function(data_ref, query_ref, window_size) {
    .Call(`_matrixprofiler_mass_pre_rcpp`, data_ref, query_ref, window_size)
}

mass_pre_abs_rcpp <- function(data_ref, query_ref, window_size) {
    .Call(`_matrixprofiler_mass_pre_abs_rcpp`, data_ref, query_ref, window_size)
}

mass_pre_weighted_rcpp <- function(data_ref, query_ref, window_size, weight) {
    .Call(`_matrixprofiler_mass_pre_weighted_rcpp`, data_ref, query_ref, window_size, weight)
}

seq_by <- function(start, end, by) {
    .Call(`_matrixprofiler_seq_by`, start, end, by)
}

std_rcpp <- function(data, na_rm = FALSE) {
    .Call(`_matrixprofiler_std_rcpp`, data, na_rm)
}

list_to_matrix <- function(x) {
    .Call(`_matrixprofiler_list_to_matrix`, x)
}

which_cpp <- function(x) {
    .Call(`_matrixprofiler_which_cpp`, x)
}

diff_lag <- function(x, lag = 1L) {
    .Call(`_matrixprofiler_diff_lag`, x, lag)
}

diff2_lag <- function(x, lag = 1L, v = 0.0) {
    .Call(`_matrixprofiler_diff2_lag`, x, lag, v)
}

fast_movsd_rcpp <- function(data, window_size) {
    .Call(`_matrixprofiler_fast_movsd_rcpp`, data, window_size)
}

fast_avg_sd_rcpp <- function(data, window_size) {
    .Call(`_matrixprofiler_fast_avg_sd_rcpp`, data, window_size)
}

mode_rcpp <- function(x) {
    .Call(`_matrixprofiler_mode_rcpp`, x)
}

znorm_rcpp <- function(data) {
    .Call(`_matrixprofiler_znorm_rcpp`, data)
}

binary_split_rcpp <- function(n) {
    .Call(`_matrixprofiler_binary_split_rcpp`, n)
}

inner_product <- function(a, b) {
    .Call(`_matrixprofiler_inner_product`, a, b)
}

sum_of_squares <- function(a) {
    .Call(`_matrixprofiler_sum_of_squares`, a)
}

muinvn_parallel_rcpp <- function(a, w) {
    .Call(`_matrixprofiler_muinvn_parallel_rcpp`, a, w)
}

muinvn_rcpp <- function(a, w) {
    .Call(`_matrixprofiler_muinvn_rcpp`, a, w)
}

fft_rcpp <- function(z, invert) {
    .Call(`_matrixprofiler_fft_rcpp`, z, invert)
}

mpx_rcpp <- function(data_ref, window_size, ez = 0.5, idxs = TRUE, euclidean = TRUE, progress = FALSE) {
    .Call(`_matrixprofiler_mpx_rcpp`, data_ref, window_size, ez, idxs, euclidean, progress)
}

mpxab_rcpp <- function(data_ref, query_ref, window_size, idxs = TRUE, euclidean = TRUE, progress = FALSE) {
    .Call(`_matrixprofiler_mpxab_rcpp`, data_ref, query_ref, window_size, idxs, euclidean, progress)
}

mpx_rcpp_parallel <- function(data_ref, window_size, ez = 0.5, idxs = TRUE, euclidean = TRUE, progress = FALSE) {
    .Call(`_matrixprofiler_mpx_rcpp_parallel`, data_ref, window_size, ez, idxs, euclidean, progress)
}

mpxab_rcpp_parallel <- function(data_ref, query_ref, window_size, idxs = TRUE, euclidean = TRUE, progress = FALSE) {
    .Call(`_matrixprofiler_mpxab_rcpp_parallel`, data_ref, query_ref, window_size, idxs, euclidean, progress)
}

scrimp_rcpp <- function(data_ref, query_ref, window_size, ez = 0.5, pre_scrimp = 0.25, progress = FALSE) {
    .Call(`_matrixprofiler_scrimp_rcpp`, data_ref, query_ref, window_size, ez, pre_scrimp, progress)
}

scrimp_rcpp_parallel <- function(data_ref, query_ref, window_size, ez = 0.5, progress = FALSE) {
    .Call(`_matrixprofiler_scrimp_rcpp_parallel`, data_ref, query_ref, window_size, ez, progress)
}

stamp_rcpp <- function(data_ref, query_ref, window_size, ez = 0.5, progress = FALSE) {
    .Call(`_matrixprofiler_stamp_rcpp`, data_ref, query_ref, window_size, ez, progress)
}

stamp_rcpp_parallel <- function(data_ref, query_ref, window_size, ez = 0.5, progress = FALSE) {
    .Call(`_matrixprofiler_stamp_rcpp_parallel`, data_ref, query_ref, window_size, ez, progress)
}

stomp_rcpp <- function(data_ref, query_ref, window_size, ez = 0.5, progress = FALSE) {
    .Call(`_matrixprofiler_stomp_rcpp`, data_ref, query_ref, window_size, ez, progress)
}

stomp_rcpp_parallel <- function(data_ref, query_ref, window_size, ez = 0.5, progress = FALSE) {
    .Call(`_matrixprofiler_stomp_rcpp_parallel`, data_ref, query_ref, window_size, ez, progress)
}

movmean_rcpp <- function(data, window_size) {
    .Call(`_matrixprofiler_movmean_rcpp`, data, window_size)
}

movvar_rcpp <- function(data, window_size) {
    .Call(`_matrixprofiler_movvar_rcpp`, data, window_size)
}

movvar2_rcpp <- function(data, window_size) {
    .Call(`_matrixprofiler_movvar2_rcpp`, data, window_size)
}

movsum_rcpp <- function(data, window_size) {
    .Call(`_matrixprofiler_movsum_rcpp`, data, window_size)
}

movsum_ogita_rcpp <- function(a, w) {
    .Call(`_matrixprofiler_movsum_ogita_rcpp`, a, w)
}

precision_test_rcpp <- function(d) {
    .Call(`_matrixprofiler_precision_test_rcpp`, d)
}

movmin_rcpp <- function(data, window_size) {
    .Call(`_matrixprofiler_movmin_rcpp`, data, window_size)
}

movmax_rcpp <- function(data, window_size) {
    .Call(`_matrixprofiler_movmax_rcpp`, data, window_size)
}

movmean_weighted_rcpp <- function(data, window_size, eps) {
    .Call(`_matrixprofiler_movmean_weighted_rcpp`, data, window_size, eps)
}

movmean_fading_rcpp <- function(data, window_size, eps) {
    .Call(`_matrixprofiler_movmean_fading_rcpp`, data, window_size, eps)
}

movsum_weighted_rcpp <- function(data, window_size, eps) {
    .Call(`_matrixprofiler_movsum_weighted_rcpp`, data, window_size, eps)
}

movsum_fading_rcpp <- function(data, window_size, eps) {
    .Call(`_matrixprofiler_movsum_fading_rcpp`, data, window_size, eps)
}

movvar_weighted_rcpp <- function(data, window_size, eps) {
    .Call(`_matrixprofiler_movvar_weighted_rcpp`, data, window_size, eps)
}

movvar_fading_rcpp <- function(data, window_size, eps) {
    .Call(`_matrixprofiler_movvar_fading_rcpp`, data, window_size, eps)
}

